experiment:
  name: "stitch_video_train"
  seed: 1

data:
  train_dataset: "../360_video/train"
  eval_dataset: "../360_video/eval"
  dataset_type: "equi_video" # "fisheye" , "equi_video" or "panorama"
  fov: 254
  canvas_size: [512, 256]
  overlap: 0.5
  jitter:
    random_seed: 1
    roll: 3.0
    pitch: 3.0
    yaw: 3.0
    translate: 0.0
    brightness: 0.2
    contrast: 0.1
    color_jitter: 0.1
    k_jitter: 0.1

train:
  epochs: 5
  optimizer: "adam"
  clip_len: 4
  batch_size: 2
  lr: 1e-4
  num_workers: 10
  grad_clip: 3
  weight_decay: 1e-4
  lambda1: 0.8
  lambda2: 0.2
  lambda3: 0.0
  lambda4: 0.1
  l_num: 1
log:
  save_interval: 2100
  log_interval: 10
  eval_interval: 2178241

model:
  homography: 1
  mean: 0.5, 0.5, 0.5
  std: 0.5, 0.5, 0.5
  local_adj_limit: 0.1
  record_weights: true
  record_warped: true
  color_correction: true